image: php:8.1

before_script:
    # Install some stuff that the image doesn't come with
    - apt update -yqq
    - apt install git libpq-dev libzip-dev zip make wget gnupg -yqq

    # Install phive
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
    - gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
    - gpg --verify phive.phar.asc phive.phar
    - chmod +x phive.phar
    - mv phive.phar /usr/local/bin/phive

    # install phpab
    - phive install phpab --global --trust-gpg-keys 0x2A8299CE842DD38C

build-job:
    script:
    - make redist
    rules:
    - if: $CI_COMMIT_BRANCH

release-job:
    script:
    - make redist
    artifacts:
        paths:
        - build/src
    rules:
    - if: $CI_COMMIT_TAG