stages:
  - prepare
  - build
  - package
  - release
  - docker-build

variables:
  PACKAGE_PATH: "build/build.tar.gz"

prepare:
  image: php:8.1
  stage: prepare
  script:
    - apt update -yqq
    - apt install git libpq-dev libzip-dev zip make wget gnupg -yqq
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
    - gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
    - gpg --verify phive.phar.asc phive.phar
    - chmod +x phive.phar
    - mv phive.phar /usr/local/bin/phive
    - phive install phpab --global --trust-gpg-keys 0x2A8299CE842DD38C
  rules:
    - if: $CI_COMMIT_BRANCH

build:
  extends: .prepare # CHANGE: Updated to correct name if you intend to use a hidden job
  stage: build
  script:
    - make tar

package:
  extends: .prepare # CHANGE: Updated to correct name if you intend to use a hidden job
  stage: package
  script:
    - make redist
    - mkdir -p package/$CI_COMMIT_REF_NAME
    - cp $PACKAGE_PATH package/$CI_COMMIT_REF_NAME/
  artifacts:
    paths:
      - package/$CI_COMMIT_REF_NAME/build.tar.gz
  rules:
    - if: $CI_COMMIT_TAG

release:
  extends: .prepare # CHANGE: Updated to correct name if you intend to use a hidden job
  stage: release
  script:
    - make redist
    - mkdir ncc_$CI_COMMIT_TAG
    - cp -r build/src/* ncc_$CI_COMMIT_TAG/
  artifacts:
    paths:
      - ncc_$CI_COMMIT_TAG/
  rules:
    - if: $CI_COMMIT_TAG

ncc-docker:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" . # CHANGE: Updated ${tag} to $CI_COMMIT_TAG
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" # CHANGE: Updated ${tag} to $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == 'master' || $CI_COMMIT_BRANCH == 'dev' # CHANGE: Added $CI_COMMIT_TAG condition
      exists:
        - Dockerfile

ncc-docker-debian:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f Dockerfile.debian --pull -t "$CI_REGISTRY_IMAGE:debian-$CI_COMMIT_TAG" . # CHANGE: Updated image tag format
    - docker push "$CI_REGISTRY_IMAGE:debian-$CI_COMMIT_TAG" # CHANGE: Updated image tag format
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == 'master' # CHANGE: Added $CI_COMMIT_TAG condition
      exists:
        - Dockerfile.debian