stages:
  - build
  - deploy

variables:
  PACKAGE_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
  PACKAGE_PATH: $CI_PROJECT_DIR/build

# Job: build
build:
  image: php:8.1
  before_script:
    - apt update -yqq
    - apt install git libpq-dev libzip-dev zip make wget gnupg -yqq
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - wget -O phive.phar.asc https://phar.io/releases/phive.phar.asc
    - gpg --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
    - gpg --verify phive.phar.asc phive.phar
    - chmod +x phive.phar
    - mv phive.phar /usr/local/bin/phive
    - phive install phpab --global --trust-gpg-keys 0x2A8299CE842DD38C
  script:
    - make tar
    - mkdir -p $PACKAGE_PATH
    - mv build/*.tar.gz $PACKAGE_PATH/$PACKAGE_NAME.tar.gz
  artifacts:
    paths:
      - $PACKAGE_PATH/$PACKAGE_NAME.tar.gz
  rules:
    - if: $CI_COMMIT_BRANCH

# Job: tag_release
tag_release:
  image: php:8.1
  script:
    - echo "Uploading the package under the new tag"
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_TAG
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    assets:
      links:
        - name: $PACKAGE_NAME.tar.gz
          url: $CI_PROJECT_URL/-/packages/$CI_PROJECT_ID/package_files/$PACKAGE_NAME.tar.gz