# NCC Default configuration file, upon installation the installer will generate a new configuration file
# for your system or update the existing configuration file and only overwriting values that are no
# longer applicable to the current version of NCC, incorrect configuration values can cause
# unexpected behavior or bugs.

ncc:
  # The default data directory that is used by NCC to store packages,
  # cache, configuration files and other generated files. This includes
  # data stored by packages using the NCC storage API.
  data_directory: "/var/ncc"

php:
  # Configuration section for the PHP configuration that NCC will use to run

  # The main executable path for PHP that NCC should use
  executable_path: "/usr/bin/php"
  
  # Enables/Disables the environment configuration feature
  # Allowing packages to install environment configurations to NCC
  # that can be loaded during runtime using the NCC API
  #
  # If disabled packages may break if they depend on this feature.
  #
  # Leaving this enabled while installing and using unknown packages
  # without reviewing their source code could lead to potential security
  # issues/backdoors, use this feature for containerized environments
  enable_environment_configurations: false

git:
  executable_path: "/usr/bin/git"

composer:
  # When enabled, NCC will use it's builtin version of composer
  # to execute composer tasks, if disabled it will fall back to
  # the `executable_path` option and attempt to use that specified
  # location of composer
  enable_internal_composer: true
  executable_path: "/home/user/composer.phar"